import type { QualityMetric } from "./types";

export const QUALITY_METRICS: QualityMetric[] = [
  {
    id: "m-pass-rate",
    name: "Pass rate",
    category: "processo",
    whatItMeasures: "% de casos de teste executados que passaram.",
    howToMeasure: "(testes que passaram ÷ testes executados) × 100, por execução ou por sprint.",
    tip: "Acompanhe a tendência ao longo do tempo, não só o número isolado — uma queda repentina diz mais do que o valor absoluto em um dia só.",
    pitfall: "Sozinho não diz nada sobre cobertura: 100% de pass rate com 5 testes manuais não significa qualidade.",
  },
  {
    id: "m-automation-coverage",
    name: "Cobertura de automação",
    category: "processo",
    whatItMeasures: "% de casos de teste ou critérios de aceite cobertos por testes automatizados.",
    howToMeasure: "casos automatizados ÷ total de casos relevantes.",
    tip: "Priorize cobrir os cenários de maior risco e maior uso primeiro, não os mais fáceis de automatizar.",
    pitfall: "% de linhas de código cobertas (line coverage) não é a mesma coisa que cobertura de comportamento — 100% de linhas cobertas pode não testar nada que importa.",
  },
  {
    id: "m-flaky-rate",
    name: "Taxa de testes flaky",
    category: "processo",
    whatItMeasures: "% de testes automatizados que falham de forma inconsistente sem mudança no código.",
    howToMeasure: "testes que falharam e depois passaram sem nenhuma alteração ÷ total de execuções.",
    tip: "Trate como dívida técnica prioritária: um teste flaky que o time aprende a ignorar destrói a confiança na suíte inteira.",
    pitfall: "Não é aceitável 'normalizar' flakiness rodando de novo até passar — isso mascara o problema em vez de resolvê-lo.",
  },
  {
    id: "m-defect-escape-rate",
    name: "Defect escape rate",
    category: "produto",
    whatItMeasures: "% de bugs encontrados em produção em vez de antes do release.",
    howToMeasure: "(bugs achados em produção ÷ total de bugs encontrados no período) × 100.",
    tip: "É uma das métricas mais fortes de eficácia do processo de teste — quanto menor, mais cedo os bugs estão sendo pegos.",
    pitfall: "Compare por período/release, não em valor absoluto: times com mais releases têm mais chances estatísticas de escape.",
  },
  {
    id: "m-defect-density",
    name: "Densidade de defeitos",
    category: "produto",
    whatItMeasures: "Quantidade de bugs por unidade de tamanho da entrega (por história, por módulo, por 1000 linhas).",
    howToMeasure: "total de bugs ÷ tamanho da entrega (histórias, pontos ou KLOC).",
    tip: "Útil para comparar módulos entre si dentro do mesmo time e priorizar onde investir mais refino e teste.",
    pitfall: "Não compare times ou projetos diferentes entre si — tamanho e complexidade variam demais para a métrica ser justa nessa comparação.",
  },
  {
    id: "m-bug-reopen-rate",
    name: "Taxa de bugs reabertos",
    category: "produto",
    whatItMeasures: "% de bugs marcados como corrigidos que voltaram a ser abertos.",
    howToMeasure: "bugs reabertos ÷ total de bugs corrigidos no período.",
    tip: "Um número alto costuma indicar que a causa raiz não está sendo tratada, só o sintoma.",
    pitfall: "Bugs reabertos por engano de fluxo no board (não por regressão real) contaminam a métrica — vale uma checagem qualitativa de tempos em tempos.",
  },
  {
    id: "m-mttr",
    name: "MTTR (Mean Time to Repair)",
    category: "fluxoDeEntrega",
    whatItMeasures: "Tempo médio entre um bug ser identificado e ser corrigido/resolvido.",
    howToMeasure: "soma do tempo de resolução de cada bug ÷ número de bugs, segmentado por severidade.",
    tip: "Segmente sempre por severidade — misturar bugs críticos com triviais esconde problemas nos críticos.",
    pitfall: "Focar só na média esconde outliers; olhe também o pior caso (p90/p95), não só a média.",
  },
  {
    id: "m-lead-time",
    name: "Lead time for changes",
    category: "fluxoDeEntrega",
    whatItMeasures: "Tempo entre o código ser commitado e chegar em produção.",
    howToMeasure: "timestamp do deploy − timestamp do primeiro commit da mudança.",
    tip: "Uma das 4 métricas DORA — quanto menor, mais rápido o time entrega valor e recebe feedback real do uso.",
    pitfall: "Otimizar isso sem acompanhar o change failure rate junto pode incentivar entregas rápidas e arriscadas.",
  },
  {
    id: "m-change-failure-rate",
    name: "Change failure rate",
    category: "fluxoDeEntrega",
    whatItMeasures: "% de deploys que causam um incidente, rollback ou hotfix em produção.",
    howToMeasure: "deploys com falha ÷ total de deploys no período.",
    tip: "Outra métrica DORA — mostra se a velocidade de entrega está vindo às custas de estabilidade.",
    pitfall: "Definir muito frouxamente o que conta como 'falha' torna a métrica inútil para comparar ao longo do tempo.",
  },
  {
    id: "m-dor-rate",
    name: "% de histórias com Definition of Ready antes da sprint",
    category: "time",
    whatItMeasures: "% de histórias que entraram na sprint já atendendo aos critérios do DoR.",
    howToMeasure: "histórias com DoR completo no início da sprint ÷ total de histórias planejadas.",
    tip: "Correlaciona fortemente com menos retrabalho e menos bugs — acompanhe junto com as sessões de refinamento.",
    pitfall: "Não vire um teatro de checkbox: a pergunta certa é se o time entendeu de fato o que vai construir, não só se marcou os itens.",
  },
  {
    id: "m-triage-time",
    name: "Tempo até a primeira resposta em bugs",
    category: "time",
    whatItMeasures: "Tempo entre um bug ser relatado e alguém do time dar a primeira resposta ou triagem.",
    howToMeasure: "timestamp da primeira resposta − timestamp do relato.",
    tip: "Impacta diretamente a percepção de qualidade de quem relata o bug, seja dev, QA ou usuário final.",
    pitfall: "Responder rápido sem investigar de verdade é pior do que não ter a métrica — acompanhe junto com a taxa de bugs reabertos.",
  },
  {
    id: "m-open-questions-per-story",
    name: "Perguntas em aberto por história no refinamento",
    category: "time",
    whatItMeasures: "Quantidade média de perguntas sem resposta clara ao final de cada sessão de refinamento.",
    howToMeasure: "some as perguntas em aberto ao fim de cada sessão de refinamento e tire a média por sprint.",
    tip: "Uma média caindo ao longo do tempo é sinal de que o time está escrevendo histórias mais claras e refinando melhor antes do planning.",
    pitfall: "Não puna quem faz perguntas — o objetivo é aumentar a clareza antes de codar, não desencorajar dúvidas.",
  },
];
